package:
  name: "conda-classic-solver"
  version: "{{ GIT_DESCRIBE_TAG }}.{{ GIT_BUILD_STR }}"

source:
  # git_url is nice in that it won't capture devenv stuff.  However, it only
  # captures committed code, so pay attention.
  git_url: ../
  folder: src/

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install src/ -vv --no-deps --no-build-isolation"

requirements:
  host:
    - python >=3.8
    - pip
    - setuptools >=71.0
    - setuptools_scm
  run:
    - python >=3.8
    - conda >=23.7.3
    - pycosat >=0.6.3

test:
  imports:
    - conda_classic_solver
  commands:
    - conda create -n test --dry-run scipy --solver=classic
    - >-
      python -c
      "import conda_classic_solver as classic;
      from importlib.metadata import version;
      assert '{{ PKG_VERSION }}' == classic.__version__ == version('conda_classic_solver'),
      '{{ PKG_VERSION }}' + f', {classic.__version__}, ' + version('conda_classic_solver')
      " || true
    # we accept errors here because GIT_DESCRIBE_TAG has some accuracy issues.
    # Shouldn't happen in production recipes; aka do not add '|| true' in the feedstock

about:
  home: https://github.com/conda/conda-classic-solver
  license: BSD-3-Clause
  license_family: BSD
  license_file: src/LICENSE
  summary: 'The `classic` solver used in `conda`.'

extra:
  recipe-maintainers:
    - jaimergp
    - jezdez
